# Generated by Django 4.2.17 on 2025-01-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_budget_from_date_budget_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='budget',
        ),
    ]
